import type { BackgroundShapeId } from "./sectionFills";

export type FillMuteIllustrationProps = {
  fill: string;
  stroke: string;
  t01Stroke: string;
  t02Stroke: string;
  t03Stroke: string;
  t04Stroke: string;
  t05Stroke: string;
  t06Stroke: string;
  t07Stroke: string;
  t08Stroke: string;
  t09Stroke: string;
  t10Stroke: string;
  t11Stroke: string;
  t12Stroke: string;
  t13Stroke: string;
  section1Stroke: string;
  section2Stroke: string;
  section3Stroke: string;
  section4Stroke: string;
  section5Stroke: string;
  section6Stroke: string;
  section1OldStroke: string;
  section2OldStroke: string;
  section3OldStroke: string;
  section4OldStroke: string;
  section5OldStroke: string;
  section6OldStroke: string;
  shapeFill: (shapeId: BackgroundShapeId) => string;
};
